# Generated by Django 3.2.7 on 2021-09-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210916_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesg',
            name='is_read',
            field=models.BooleanField(default=True),
        ),
    ]
